#include "globals.h"


EFI_SYSTEM_TABLE* gST = NULL;
EFI_BOOT_SERVICES* gBS = NULL;
EFI_RUNTIME_SERVICES* gRS = NULL;

EFI_DISK_IO_PROTOCOL* DiskIo = NULL;
EFI_BLOCK_IO_PROTOCOL* BlockIo = NULL;

EFI_GUID gEfiBlockIoProtocolGuid = EFI_BLOCK_IO_PROTOCOL_GUID;
EFI_GUID gEfiDiskIoProtocolGuid = EFI_DISK_IO_PROTOCOL_GUID;